FROM python:3.12-slim

WORKDIR /app

# Отключаем создание .pyc файлов и включаем сразу вывод логов в консоль
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Копируем и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь исходный код бэкенда в контейнер
COPY . .

# Открываем порт для приложения
EXPOSE 8000

# Запускаем FastAPI через uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]